import { JobStatus } from '../jobs/typing.d';
import type { ActiveJob } from './typing.d';

export const rawActiveJobs: ActiveJob[] = [
  {
    id: 'aj-001',
    title: 'SPA Financial Dashboard',
    description: 'Xây dựng ứng dụng web SPA hỗ trợ người dùng theo dõi danh mục đầu tư chứng khoán và quản lý chi tiêu hàng ngày với biểu đồ tương tác và dữ liệu thời gian thực.',
    budget: '$4,000',
    client: 'TechVentures Inc.',
    status: JobStatus.InProgress,
    statusLabel: 'In Progress',
    progress: 65,
    startDate: '01/04/2026',
    deadline: '28/04/2026',
    category: 'Frontend',
  },
  {
    id: 'aj-002',
    title: 'E-commerce UI/UX Redesign',
    description: 'Redesign the entire user experience for a high-traffic e-commerce platform, focusing on conversion rate optimisation and mobile-first responsive layouts.',
    budget: '$2,400',
    client: 'ShopEase LLC',
    status: JobStatus.InProgress,
    statusLabel: 'In Progress',
    progress: 40,
    startDate: '10/04/2026',
    deadline: '10/06/2026',
    category: 'Design',
  },
  {
    id: 'aj-003',
    title: 'Payment Gateway Integration',
    description: 'Implement a secure payment gateway integration with Stripe and PayPal APIs, including webhook handling and full PCI-DSS compliance review.',
    budget: '$850',
    client: 'FinPay Solutions',
    status: JobStatus.Revision,
    statusLabel: 'Revision',
    progress: 85,
    startDate: '18/04/2026',
    deadline: '25/04/2026',
    category: 'Backend',
  },
  {
    id: 'aj-004',
    title: 'Smart Contract Audit – DeFi Protocol',
    description: 'Comprehensive security audit of Solidity smart contracts for a new DeFi yield-farming protocol, including reentrancy and integer-overflow analysis.',
    budget: '$5,000',
    client: 'ChainSafe DeFi',
    status: JobStatus.Completed,
    statusLabel: 'Completed',
    progress: 100,
    startDate: '07/04/2026',
    deadline: '17/04/2026',
    category: 'Security',
  },
  {
    id: 'aj-005',
    title: 'Mobile App Backend API',
    description: 'Design and implement a RESTful Node.js/Express backend with PostgreSQL for a cross-platform fitness tracking mobile application.',
    budget: '$3,200',
    client: 'FitTrack Labs',
    status: JobStatus.InProgress,
    statusLabel: 'In Progress',
    progress: 20,
    startDate: '22/04/2026',
    deadline: '22/05/2026',
    category: 'Backend',
  },
];
