import { JobStatus } from './typing.d';
import type { Job } from './typing.d';

export const rawFreelancerName = "Nguyen Quang Dat";

export const rawJobs: Job[] = [
  {
    title: 'web',
    description: 'Xây dựng một ứng dụng web Single Page Application (SPA) hỗ trợ người dùng cá nhân theo dõi danh mục đầu tư chứng khoán và quản lý chi tiêu hàng ngày. Dự án tập trung vào việc hiển thị dữ liệu trực quan thông qua các biểu đồ tương tác, giúp người dùng có cái nhìn tổng quan về sức khỏe tài chính...',
    budget: '$4,000',
    category: 'frontend',
    level: 'Expert',
    location: 'Remote',
    type: 'Fixed Price',
    timestamp: '2026-04-14T10:00:00Z',
    status: JobStatus.Active,
    statusLabel: 'Active',
    postDate: '14/4/2026',
    deadline: '4 weeks',
    requirements: [
      'Framework: React.js (Sử dụng Vite để tối ưu tốc độ build). State Management: Redux Toolkit hoặc React Context API để quản lý dữ liệu toàn cục. UI Library: Tailwind CSS kết hợp với Ant Design hoặc Shadcn/UI để tạo giao diện chuyên nghiệp',
      'nhanh chóng. Data Visualization: Chart.js hoặc Recharts để vẽ biểu đồ tăng trưởng và phân bổ tài sản. API Integration: Axios để kết nối với các dịch vụ dữ liệu tài chính (hoặc mock data qua JSON Server). Storage: LocalStorage để lưu trữ dữ liệu tạm thời của người dùng nếu chưa có Backend hoàn chỉnh.',
    ],
  },
  {
    title: 'E-commerce UI/UX Design Redesign',
    description: 'Redesign the entire user experience for a high-traffic e-commerce platform.',
    budget: '$2,400',
    category: 'Design',
    level: 'Intermediate',
    location: 'Onsite',
    type: 'Hourly',
    timestamp: '2026-04-15T12:00:00Z',
    status: JobStatus.InProgress,
    statusLabel: 'In Progress',
    postDate: '15/4/2026',
    deadline: '2 months',
  },
  {
    title: 'API Integration for Payment Gateway',
    description: 'Implement a secure payment gateway integration using Stripe and PayPal APIs.',
    budget: '$850',
    category: 'Backend',
    level: 'Expert',
    location: 'Remote',
    type: 'Fixed Price',
    timestamp: '2026-04-16T09:00:00Z',
    status: JobStatus.Revision,
    statusLabel: 'Revision',
    postDate: '16/4/2026',
    deadline: '1 week',
  },
  {
    title: 'Smart Contract Audit',
    description: 'Comprehensive audit of smart contracts for a new DeFi protocol.',
    budget: '$5,000',
    category: 'Security',
    level: 'Expert',
    location: 'Remote',
    type: 'Fixed Price',
    timestamp: '2026-04-17T15:00:00Z',
    status: JobStatus.Completed,
    statusLabel: 'Completed',
    postDate: '17/4/2026',
    deadline: '10 days',
  },
];
